version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    links:
      - php
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/laravel:/var/www/laravel
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src/laravel/:/var/www/laravel
    links:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - 3316:3306
    env_file:
      - docker/mysql/.env